use crate::types::resource::{MetaItem, MetaItemBehaviorHints, MetaItemPreview, PosterShape};
use crate::unit_tests::serde::default_tokens_ext::DefaultTokens;
use chrono::{TimeZone, Utc};
use serde_test::{assert_de_tokens, assert_tokens, Token};
use url::Url;

#[test]
fn meta_item() {
    assert_tokens(
        &vec![
            MetaItem {
                preview: MetaItemPreview {
                    id: "tt:123456".to_owned(),
                    r#type: "movie".to_owned(),
                    name: "name".to_owned(),
                    poster: Some(Url::parse("http://poster/").unwrap()),
                    background: Some(Url::parse("http://background/").unwrap()),
                    logo: Some(Url::parse("http://logo/").unwrap()),
                    description: Some("description".to_owned()),
                    release_info: Some("release_info".to_owned()),
                    runtime: Some("runtime".to_owned()),
                    released: Some(Utc.with_ymd_and_hms(2020, 1, 1, 0, 0, 0).unwrap()),
                    poster_shape: PosterShape::default(),
                    links: vec![],
                    trailer_streams: vec![],
                    behavior_hints: MetaItemBehaviorHints::default(),
                },
                videos: vec![],
            },
            MetaItem {
                preview: MetaItemPreview {
                    id: "tt:654321".to_owned(),
                    r#type: "movie".to_owned(),
                    name: "name".to_owned(),
                    poster: None,
                    background: None,
                    logo: None,
                    description: None,
                    release_info: None,
                    runtime: None,
                    released: None,
                    poster_shape: PosterShape::default(),
                    links: vec![],
                    trailer_streams: vec![],
                    behavior_hints: MetaItemBehaviorHints::default(),
                },
                videos: vec![],
            },
        ],
        &[
            vec![Token::Seq { len: Some(2) }],
            vec![
                Token::Map { len: None },
                Token::Str("id"),
                Token::Str("tt:123456"),
                Token::Str("type"),
                Token::Str("movie"),
                Token::Str("name"),
                Token::Str("name"),
                Token::Str("poster"),
                Token::Some,
                Token::Str("http://poster/"),
                Token::Str("background"),
                Token::Some,
                Token::Str("http://background/"),
                Token::Str("logo"),
                Token::Some,
                Token::Str("http://logo/"),
                Token::Str("description"),
                Token::Some,
                Token::Str("description"),
                Token::Str("releaseInfo"),
                Token::Some,
                Token::Str("release_info"),
                Token::Str("runtime"),
                Token::Some,
                Token::Str("runtime"),
                Token::Str("released"),
                Token::Some,
                Token::Str("2020-01-01T00:00:00Z"),
                Token::Str("posterShape"),
            ],
            PosterShape::default_tokens(),
            vec![
                Token::Str("links"),
                // Token::None,
                // Token::Some,
                Token::Seq { len: Some(0) },
                Token::SeqEnd,
                Token::Str("trailerStreams"),
                // Token::None,
                // Token::Some,
                Token::Seq { len: Some(0) },
                Token::SeqEnd,
                Token::Str("behaviorHints"),
                // Token::None,
            ],
            MetaItemBehaviorHints::default_tokens(),
            vec![
                Token::Str("videos"),
                // Token::None,
                Token::Some,
                Token::Seq { len: Some(0) },
                Token::SeqEnd,
                Token::MapEnd,
            ],
            vec![
                Token::Map { len: None },
                Token::Str("id"),
                Token::Str("tt:654321"),
                Token::Str("type"),
                Token::Str("movie"),
                Token::Str("name"),
                Token::Str("name"),
                Token::Str("poster"),
                Token::None,
                Token::Str("background"),
                Token::None,
                Token::Str("logo"),
                Token::None,
                Token::Str("description"),
                Token::None,
                Token::Str("releaseInfo"),
                Token::None,
                Token::Str("runtime"),
                Token::None,
                Token::Str("released"),
                Token::None,
                Token::Str("posterShape"),
            ],
            PosterShape::default_tokens(),
            vec![
                Token::Str("links"),
                Token::Seq { len: Some(0) },
                Token::SeqEnd,
                Token::Str("trailerStreams"),
                Token::Seq { len: Some(0) },
                Token::SeqEnd,
                Token::Str("behaviorHints"),
            ],
            MetaItemBehaviorHints::default_tokens(),
            vec![
                Token::Str("videos"),
                Token::Some,
                Token::Seq { len: Some(0) },
                Token::SeqEnd,
                Token::MapEnd,
            ],
            vec![Token::SeqEnd],
        ]
        .concat(),
    );
    assert_de_tokens(
        &[
            MetaItem {
                preview: MetaItemPreview {
                    id: "id".into(),
                    r#type: "type".to_owned(),
                    name: "".to_owned(),
                    poster: None,
                    background: None,
                    logo: None,
                    description: None,
                    release_info: None,
                    runtime: None,
                    released: Some(Utc.with_ymd_and_hms(1970, 1, 1, 0, 0, 10).unwrap()),
                    poster_shape: PosterShape::default(),
                    links: vec![],
                    trailer_streams: vec![],
                    behavior_hints: MetaItemBehaviorHints::default(),
                },
                videos: vec![],
            },
            MetaItem {
                preview: MetaItemPreview {
                    id: "id".into(),
                    r#type: "type".to_owned(),
                    name: "".to_owned(),
                    poster: None,
                    background: None,
                    logo: None,
                    description: None,
                    release_info: Some("1".to_owned()),
                    runtime: Some("2".to_owned()),
                    released: None,
                    poster_shape: PosterShape::default(),
                    links: vec![],
                    trailer_streams: vec![],
                    behavior_hints: MetaItemBehaviorHints::default(),
                },
                videos: vec![],
            },
        ],
        &[
            Token::Seq { len: Some(2) },
            Token::Struct {
                name: "MetaItem",
                len: 3,
            },
            Token::Str("id"),
            Token::Str("id"),
            Token::Str("type"),
            Token::Str("type"),
            Token::Str("released"),
            Token::Some,
            Token::I64(10_000),
            // videos field
            Token::Str("videos"),
            Token::None,
            Token::StructEnd,
            Token::Struct {
                name: "MetaItem",
                len: 4,
            },
            Token::Str("id"),
            Token::Str("id"),
            Token::Str("type"),
            Token::Str("type"),
            Token::Str("releaseInfo"),
            Token::I32(1),
            Token::Str("runtime"),
            Token::I32(2),
            // videos field
            Token::Str("videos"),
            Token::None,
            Token::StructEnd,
            Token::SeqEnd,
        ],
    );
}

#[test]
fn meta_item_de_urls_none_when_empty() {
    assert_de_tokens(
        &MetaItem {
            preview: MetaItemPreview {
                id: "id".into(),
                r#type: "type".to_owned(),
                name: "".to_owned(),
                poster: None,
                background: None,
                logo: None,
                description: None,
                release_info: None,
                runtime: None,
                released: None,
                poster_shape: PosterShape::default(),
                links: vec![],
                trailer_streams: vec![],
                behavior_hints: MetaItemBehaviorHints::default(),
            },
            videos: vec![],
        },
        &[
            Token::Struct {
                name: "MetaItem",
                len: 2,
            },
            Token::Str("id"),
            Token::Str("id"),
            Token::Str("type"),
            Token::Str("type"),
            Token::Str("poster"),
            Token::Some,
            Token::Str(""),
            Token::Str("background"),
            Token::Some,
            Token::Str(""),
            Token::Str("logo"),
            Token::Some,
            Token::Str(""),
            Token::Str("videos"),
            Token::None,
            Token::StructEnd,
        ],
    );
}
