name: MSRV build

on:
  push:
  # will checkout the default branch `development`
  schedule:
    # run every Friday at 17:00
    - cron: '00 17 * * 5'
  # Or ran manually
  workflow_dispatch:

# Stops the running workflow of previous pushes
concurrency:
  # cancel per workflow
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  RUST_MSRV_VERSION: '1.70'

jobs:
  build:
    name: Test and build
    runs-on: ubuntu-latest

    steps:
    - name: Rust setup (MSRV)
      uses: dtolnay/rust-toolchain@master
      with:
        toolchain: ${{ env.RUST_MSRV_VERSION }}

    - uses: Swatinem/rust-cache@v2

    - name: Checkout
      uses: actions/checkout@v4

    - run: cargo check
    - run: cargo test